### ISSUE TITLE
Update to 2024 WPILib

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2022_Offbot_Code#135]
This project needs to be updated to 2024 WPILib

In this process we should also clean up some of the code by removing components unnecessary demos.

Use existing [2024-WPILib branch](https://github.com/FRCTeam3255/2022_Offbot_Code/tree/2024-WPILib) as it as already been prepped using the WPILib import tool.

```[tasklist]
### Tasks
- [x] Remove Autos
- [x] Remove all Pneumatic References (solenoids)
- [x] Remove switchboard joystick
- [x] Update joystick buttons to use new button calls
- [x] Remove odemetry
- [x] Remove vision
```
